/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonasRouteImport } from './routes/zonas'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as PlanoSalonRouteImport } from './routes/plano-salon'
import { Route as MesasRouteImport } from './routes/mesas'
import { Route as ListaEsperaRouteImport } from './routes/lista-espera'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as BloqueosRouteImport } from './routes/bloqueos'
import { Route as IndexRouteImport } from './routes/index'

const ZonasRoute = ZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoSalonRoute = PlanoSalonRouteImport.update({
  id: '/plano-salon',
  path: '/plano-salon',
  getParentRoute: () => rootRouteImport,
} as any)
const MesasRoute = MesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaEsperaRoute = ListaEsperaRouteImport.update({
  id: '/lista-espera',
  path: '/lista-espera',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueosRoute = BloqueosRouteImport.update({
  id: '/bloqueos',
  path: '/bloqueos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bloqueos': typeof BloqueosRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/lista-espera': typeof ListaEsperaRoute
  '/mesas': typeof MesasRoute
  '/plano-salon': typeof PlanoSalonRoute
  '/reservas': typeof ReservasRoute
  '/zonas': typeof ZonasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bloqueos': typeof BloqueosRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/lista-espera': typeof ListaEsperaRoute
  '/mesas': typeof MesasRoute
  '/plano-salon': typeof PlanoSalonRoute
  '/reservas': typeof ReservasRoute
  '/zonas': typeof ZonasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bloqueos': typeof BloqueosRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/lista-espera': typeof ListaEsperaRoute
  '/mesas': typeof MesasRoute
  '/plano-salon': typeof PlanoSalonRoute
  '/reservas': typeof ReservasRoute
  '/zonas': typeof ZonasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bloqueos'
    | '/clientes'
    | '/dashboard'
    | '/lista-espera'
    | '/mesas'
    | '/plano-salon'
    | '/reservas'
    | '/zonas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bloqueos'
    | '/clientes'
    | '/dashboard'
    | '/lista-espera'
    | '/mesas'
    | '/plano-salon'
    | '/reservas'
    | '/zonas'
  id:
    | '__root__'
    | '/'
    | '/bloqueos'
    | '/clientes'
    | '/dashboard'
    | '/lista-espera'
    | '/mesas'
    | '/plano-salon'
    | '/reservas'
    | '/zonas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BloqueosRoute: typeof BloqueosRoute
  ClientesRoute: typeof ClientesRoute
  DashboardRoute: typeof DashboardRoute
  ListaEsperaRoute: typeof ListaEsperaRoute
  MesasRoute: typeof MesasRoute
  PlanoSalonRoute: typeof PlanoSalonRoute
  ReservasRoute: typeof ReservasRoute
  ZonasRoute: typeof ZonasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zonas': {
      id: '/zonas'
      path: '/zonas'
      fullPath: '/zonas'
      preLoaderRoute: typeof ZonasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano-salon': {
      id: '/plano-salon'
      path: '/plano-salon'
      fullPath: '/plano-salon'
      preLoaderRoute: typeof PlanoSalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesas': {
      id: '/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof MesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-espera': {
      id: '/lista-espera'
      path: '/lista-espera'
      fullPath: '/lista-espera'
      preLoaderRoute: typeof ListaEsperaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueos': {
      id: '/bloqueos'
      path: '/bloqueos'
      fullPath: '/bloqueos'
      preLoaderRoute: typeof BloqueosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BloqueosRoute: BloqueosRoute,
  ClientesRoute: ClientesRoute,
  DashboardRoute: DashboardRoute,
  ListaEsperaRoute: ListaEsperaRoute,
  MesasRoute: MesasRoute,
  PlanoSalonRoute: PlanoSalonRoute,
  ReservasRoute: ReservasRoute,
  ZonasRoute: ZonasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
